### ISSUE TITLE
неверное условие цикла

### ISSUE THREAD

**Issue by nekit-bes** [evgenkarlson/COMPLETED_PISCINE_C#11]
https://github.com/evgenkarlson/COMPLETED_PISCINE_C/blob/33b35c5e989605319e87f16ec741343fb6338ec0/Exam_C/1-3____rev_print.c#L62

Первый символ str[0] не напечатается, нужно поменять условие на:  while(i >= 0)

**Comment by evgenkarlson** [comment]
Oh, thanks! Corrected.
Apparently in a hurry, I stuck the postdecrement i-- after calling the write() function.
