### ISSUE TITLE
 Нужно добавить строку

### ISSUE THREAD

**Issue by nekit-bes** [evgenkarlson/COMPLETED_PISCINE_C#12]
https://github.com/evgenkarlson/COMPLETED_PISCINE_C/blob/33b35c5e989605319e87f16ec741343fb6338ec0/Exam_C/1-3____rev_print.c#L61
нужно добавить в следующей строке: 
i -= 1; 
Из за того что i указывает на '\0'

Этого не видно если выполнять команду без  | cat -e

**Comment by evgenkarlson** [comment]
Oh, thanks! Corrected.
Apparently in a hurry, I stuck the postdecrement i-- after calling the write() function.

**Comment by evgenkarlson** [comment]
https://github.com/evgenkarlson/COMPLETED_PISCINE_C/blob/master/Exam_C/1-3____rev_print.c
